# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pichature', '0004_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='label',
            field=models.SlugField(default='main', unique=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(),
        ),
    ]
