# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pichature', '0005_auto_20170517_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
